In [1]:
import sys, os
path = os.path.abspath('../src')
sys.path.insert(0, path)

In [2]:
from gedih3.config import GH3_DEFAULT_DOWNLOAD_DIR, GH3_DEFAULT_SOC_DIR, GEDI_START_DATE
from gedih3.gedidriver import soc_file_tree, dask_h5_merged
from gedih3.gh3builder import h3_index_df, build_h3db_from_soc

In [3]:
from dask.distributed import Client
import dask.dataframe
import dask_geopandas
client = Client(processes=True, threads_per_worker=1, n_workers=20)
client

2025-10-06 17:02:36,174 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle f39b26f3779487b891e93cd2f82a33d0 initialized by task ('shuffle-transfer-f39b26f3779487b891e93cd2f82a33d0', 20) executed on worker tcp://127.0.0.1:46299
2025-10-06 17:03:35,448 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle f39b26f3779487b891e93cd2f82a33d0 deactivated due to stimulus 'task-finished-1759784615.4454129'
2025-10-06 17:04:55,864 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7bc7a8dd6a24bfed204961eab08704cb initialized by task ('shuffle-transfer-7bc7a8dd6a24bfed204961eab08704cb', 2995) executed on worker tcp://127.0.0.1:35737
2025-10-06 17:05:51,157 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7bc7a8dd6a24bfed204961eab08704cb deactivated due to stimulus 'task-finished-1759784751.156804'
2025-10-06 17:07:27,565 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 8848fa0ff4902db1e7de7052d348c5e7 initialized by task ('shuffle-transfer-8848fa0ff4902db1e7de7052d348c5e7', 303) executed on worker tcp://127.0.0.1:42485
2025-10-06 17:08:21,890 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 8848fa0ff4902db1e7de7052d348c5e7 deactivated due to stimulus 'task-finished-1759784901.8881435'
2025-10-06 17:08:54,798 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 04813a28c34ebcf44f57cfe250a5eac2 initialized by task ('shuffle-transfer-04813a28c34ebcf44f57cfe250a5eac2', 13) executed on worker tcp://127.0.0.1:38013
2025-10-06 17:09:02,375 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 04813a28c34ebcf44f57cfe250a5eac2 deactivated due to stimulus 'task-finished-1759784942.3742092'
2025-10-06 17:09:16,052 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 257b4374d77fb3c34a108a43f36713b5 initialized by task ('shuffle-transfer-257b4374d77fb3c34a108a43f36713b5', 13) executed on worker tcp://127.0.0.1:38013
2025-10-06 17:09:22,964 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 257b4374d77fb3c34a108a43f36713b5 deactivated due to stimulus 'task-finished-1759784962.9621902'
2025-10-06 17:09:48,450 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a7d1f35a9e646f3b9b14942a0fa697da initialized by task ('shuffle-transfer-a7d1f35a9e646f3b9b14942a0fa697da', 2957) executed on worker tcp://127.0.0.1:46299
2025-10-06 17:10:42,909 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle a7d1f35a9e646f3b9b14942a0fa697da deactivated due to stimulus 'task-finished-1759785042.7767031'
2025-10-06 17:10:56,850 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle e66603f2162033ef6616cd407452f2f7 initialized by task ('shuffle-transfer-e66603f2162033ef6616cd407452f2f7', 2938) executed on worker tcp://127.0.0.1:46299
2025-10-06 17:11:48,905 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle e66603f2162033ef6616cd407452f2f7 deactivated due to stimulus 'task-finished-1759785108.9029865'
2025-10-06 17:12:06,929 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 5fbc61bdfee32278ae27c40c7884c582 initialized by task ('shuffle-transfer-5fbc61bdfee32278ae27c40c7884c582', 13) executed on worker tcp://127.0.0.1:35867
2025-10-06 17:12:14,423 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 5fbc61bdfee32278ae27c40c7884c582 deactivated due to stimulus 'task-finished-1759785134.420974'
2025-10-06 17:12:22,023 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3ac1d958613a0f582092f0e1498b9ddb initialized by task ('shuffle-transfer-3ac1d958613a0f582092f0e1498b9ddb', 13) executed on worker tcp://127.0.0.1:38013
2025-10-06 17:12:28,642 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3ac1d958613a0f582092f0e1498b9ddb deactivated due to stimulus 'task-finished-1759785148.6401477'
2025-10-06 17:14:05,266 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c486dd36fee18a49586150ac958d282e initialized by task ('shuffle-transfer-c486dd36fee18a49586150ac958d282e', 13) executed on worker tcp://127.0.0.1:38013
2025-10-06 17:14:12,578 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c486dd36fee18a49586150ac958d282e deactivated due to stimulus 'task-finished-1759785252.5761142'
2025-10-06 17:30:10,690 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c08d2616f389c2e7a9701a0e92583987 initialized by task ('shuffle-transfer-c08d2616f389c2e7a9701a0e92583987', 11) executed on worker tcp://127.0.0.1:43847
2025-10-06 17:30:17,293 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c08d2616f389c2e7a9701a0e92583987 deactivated due to stimulus 'task-finished-1759786217.2915516'

In [30]:
ddf = dask_geopandas.read_parquet('../tmp/h3', gather_spatial_partitions=False)
ddf

Dask GeoDataFrame Structure:
               shot_number lat_lowestmode_l2a rh_000_l2a rh_001_l2a rh_002_l2a rh_003_l2a rh_004_l2a rh_005_l2a rh_006_l2a rh_007_l2a rh_008_l2a rh_009_l2a rh_010_l2a rh_011_l2a rh_012_l2a rh_013_l2a rh_014_l2a rh_015_l2a rh_016_l2a rh_017_l2a rh_018_l2a rh_019_l2a rh_020_l2a rh_021_l2a rh_022_l2a rh_023_l2a rh_024_l2a rh_025_l2a rh_026_l2a rh_027_l2a rh_028_l2a rh_029_l2a rh_030_l2a rh_031_l2a rh_032_l2a rh_033_l2a rh_034_l2a rh_035_l2a rh_036_l2a rh_037_l2a rh_038_l2a rh_039_l2a rh_040_l2a rh_041_l2a rh_042_l2a rh_043_l2a rh_044_l2a rh_045_l2a rh_046_l2a rh_047_l2a rh_048_l2a rh_049_l2a rh_050_l2a rh_051_l2a rh_052_l2a rh_053_l2a rh_054_l2a rh_055_l2a rh_056_l2a rh_057_l2a rh_058_l2a rh_059_l2a rh_060_l2a rh_061_l2a rh_062_l2a rh_063_l2a rh_064_l2a rh_065_l2a rh_066_l2a rh_067_l2a rh_068_l2a rh_069_l2a rh_070_l2a rh_071_l2a rh_072_l2a rh_073_l2a rh_074_l2a rh_075_l2a rh_076_l2a rh_077_l2a rh_078_l2a rh_079_l2a rh_080_l2a rh_081_l2a rh_082_l2a rh_083_l2a rh_084_l2a rh_085_l2a rh_086_l2a rh_087_l2a rh_088_l2a rh_089_l2a rh_090_l2a rh_091_l2a rh_092_l2a rh_093_l2a rh_094_l2a rh_095_l2a rh_096_l2a rh_097_l2a rh_098_l2a rh_099_l2a rh_100_l2a delta_time_l2a lon_lowestmode_l2a quality_flag_l2a elev_lowestmode_l2a root_beam_l2a root_file_l2a cover_z_000_l2b cover_z_001_l2b cover_z_002_l2b cover_z_003_l2b cover_z_004_l2b cover_z_005_l2b cover_z_006_l2b cover_z_007_l2b cover_z_008_l2b cover_z_009_l2b cover_z_010_l2b cover_z_011_l2b cover_z_012_l2b cover_z_013_l2b cover_z_014_l2b cover_z_015_l2b cover_z_016_l2b cover_z_017_l2b cover_z_018_l2b cover_z_019_l2b cover_z_020_l2b cover_z_021_l2b cover_z_022_l2b cover_z_023_l2b cover_z_024_l2b cover_z_025_l2b cover_z_026_l2b cover_z_027_l2b cover_z_028_l2b cover_z_029_l2b fhd_normal_l2b root_beam_l2b root_file_l2b agbd_l4a root_beam_l4a root_file_l4a algorithm_run_flag_l4c beam_l4c channel_l4c degrade_flag_l4c delta_time_l4c elev_lowestmode_l4c elev_outlier_flag_l4c fhd_normal_l4c geolocation/elev_lowestmode_a1_l4c geolocation/elev_lowestmode_a10_l4c geolocation/elev_lowestmode_a2_l4c geolocation/elev_lowestmode_a3_l4c geolocation/elev_lowestmode_a4_l4c geolocation/elev_lowestmode_a5_l4c geolocation/elev_lowestmode_a6_l4c geolocation/lat_lowestmode_a1_l4c geolocation/lat_lowestmode_a10_l4c geolocation/lat_lowestmode_a2_l4c geolocation/lat_lowestmode_a3_l4c geolocation/lat_lowestmode_a4_l4c geolocation/lat_lowestmode_a5_l4c geolocation/lat_lowestmode_a6_l4c geolocation/lon_lowestmode_a1_l4c geolocation/lon_lowestmode_a10_l4c geolocation/lon_lowestmode_a2_l4c geolocation/lon_lowestmode_a3_l4c geolocation/lon_lowestmode_a4_l4c geolocation/lon_lowestmode_a5_l4c geolocation/lon_lowestmode_a6_l4c geolocation/sensitivity_a1_l4c geolocation/sensitivity_a10_l4c geolocation/sensitivity_a2_l4c geolocation/sensitivity_a3_l4c geolocation/sensitivity_a4_l4c geolocation/sensitivity_a5_l4c geolocation/sensitivity_a6_l4c geolocation/shot_number_l4c geolocation/stale_return_flag_l4c l2_quality_flag_l4c land_cover_data/landsat_treecover_l4c land_cover_data/landsat_water_persistence_l4c land_cover_data/leaf_off_doy_l4c land_cover_data/leaf_off_flag_l4c land_cover_data/leaf_on_cycle_l4c land_cover_data/leaf_on_doy_l4c land_cover_data/pft_class_l4c land_cover_data/region_class_l4c land_cover_data/shot_number_l4c land_cover_data/urban_focal_window_size_l4c land_cover_data/urban_proportion_l4c land_cover_data/worldcover_class_l4c lat_lowestmode_l4c lon_lowestmode_l4c master_frac_l4c master_int_l4c selected_algorithm_l4c sensitivity_l4c solar_elevation_l4c surface_flag_l4c wsci_l4c wsci_pi_lower_l4c wsci_pi_upper_l4c wsci_prediction/algorithm_run_flag_a1_l4c wsci_prediction/algorithm_run_flag_a10_l4c wsci_prediction/algorithm_run_flag_a2_l4c wsci_prediction/algorithm_run_flag_a3_l4c wsci_prediction/algorithm_run_flag_a4_l4c wsci_prediction/algorithm_run_flag_a5_l4c wsci_prediction/algorithm_run_flag_a6_l4c wsci_prediction/l2_quality_flag_a1_l4c wsci_prediction/l2_quality_flag_a10_l4c wsci_prediction/l2_quality_flag_a2_l4c wsci_prediction/l2_quality_flag_a3_l4c wsci_prediction/l2_quality_flag_a4_l4c wsci_prediction/l2_quality_flag_a5_l4c wsci_prediction/l2_quality_flag_a6_l4c wsci_prediction/shot_number_l4c wsci_prediction/wsci_a1_l4c wsci_prediction/wsci_a10_l4c wsci_prediction/wsci_a2_l4c wsci_prediction/wsci_a3_l4c wsci_prediction/wsci_a4_l4c wsci_prediction/wsci_a5_l4c wsci_prediction/wsci_a6_l4c wsci_prediction/wsci_pi_lower_a1_l4c wsci_prediction/wsci_pi_lower_a10_l4c wsci_prediction/wsci_pi_lower_a2_l4c wsci_prediction/wsci_pi_lower_a3_l4c wsci_prediction/wsci_pi_lower_a4_l4c wsci_prediction/wsci_pi_lower_a5_l4c wsci_prediction/wsci_pi_lower_a6_l4c wsci_prediction/wsci_pi_upper_a1_l4c wsci_prediction/wsci_pi_upper_a10_l4c wsci_prediction/wsci_pi_upper_a2_l4c wsci_prediction/wsci_pi_upper_a3_l4c wsci_prediction/wsci_pi_upper_a4_l4c wsci_prediction/wsci_pi_upper_a5_l4c wsci_prediction/wsci_pi_upper_a6_l4c wsci_prediction/wsci_quality_flag_a1_l4c wsci_prediction/wsci_quality_flag_a10_l4c wsci_prediction/wsci_quality_flag_a2_l4c wsci_prediction/wsci_quality_flag_a3_l4c wsci_prediction/wsci_quality_flag_a4_l4c wsci_prediction/wsci_quality_flag_a5_l4c wsci_prediction/wsci_quality_flag_a6_l4c wsci_prediction/wsci_xy_a1_l4c wsci_prediction/wsci_xy_a10_l4c wsci_prediction/wsci_xy_a2_l4c wsci_prediction/wsci_xy_a3_l4c wsci_prediction/wsci_xy_a4_l4c wsci_prediction/wsci_xy_a5_l4c wsci_prediction/wsci_xy_a6_l4c wsci_prediction/wsci_xy_pi_lower_a1_l4c wsci_prediction/wsci_xy_pi_lower_a10_l4c wsci_prediction/wsci_xy_pi_lower_a2_l4c wsci_prediction/wsci_xy_pi_lower_a3_l4c wsci_prediction/wsci_xy_pi_lower_a4_l4c wsci_prediction/wsci_xy_pi_lower_a5_l4c wsci_prediction/wsci_xy_pi_lower_a6_l4c wsci_prediction/wsci_xy_pi_upper_a1_l4c wsci_prediction/wsci_xy_pi_upper_a10_l4c wsci_prediction/wsci_xy_pi_upper_a2_l4c wsci_prediction/wsci_xy_pi_upper_a3_l4c wsci_prediction/wsci_xy_pi_upper_a4_l4c wsci_prediction/wsci_xy_pi_upper_a5_l4c wsci_prediction/wsci_xy_pi_upper_a6_l4c wsci_prediction/wsci_z_a1_l4c wsci_prediction/wsci_z_a10_l4c wsci_prediction/wsci_z_a2_l4c wsci_prediction/wsci_z_a3_l4c wsci_prediction/wsci_z_a4_l4c wsci_prediction/wsci_z_a5_l4c wsci_prediction/wsci_z_a6_l4c wsci_prediction/wsci_z_pi_lower_a1_l4c wsci_prediction/wsci_z_pi_lower_a10_l4c wsci_prediction/wsci_z_pi_lower_a2_l4c wsci_prediction/wsci_z_pi_lower_a3_l4c wsci_prediction/wsci_z_pi_lower_a4_l4c wsci_prediction/wsci_z_pi_lower_a5_l4c wsci_prediction/wsci_z_pi_lower_a6_l4c wsci_prediction/wsci_z_pi_upper_a1_l4c wsci_prediction/wsci_z_pi_upper_a10_l4c wsci_prediction/wsci_z_pi_upper_a2_l4c wsci_prediction/wsci_z_pi_upper_a3_l4c wsci_prediction/wsci_z_pi_upper_a4_l4c wsci_prediction/wsci_z_pi_upper_a5_l4c wsci_prediction/wsci_z_pi_upper_a6_l4c wsci_quality_flag_l4c wsci_xy_l4c wsci_xy_pi_lower_l4c wsci_xy_pi_upper_l4c wsci_z_l4c wsci_z_pi_lower_l4c wsci_z_pi_upper_l4c root_beam_l4c root_file_l4c        datetime  geometry            h3_03             year
npartitions=21
                    uint64            float64    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32        float64            float64            uint8             float32        string        string         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32         float32        float32        string        string  float32        string        string                  uint8   uint16       uint8            uint8        float64             float32                 uint8        float64                            float32                             float32                            float32                            float32                            float32                            float32                            float32                           float64                            float64                           float64                           float64                           float64                           float64                           float64                           float64                            float64                           float64                           float64                           float64                           float64                           float64                        float32                         float32                        float32                        float32                        float32                        float32                        float32                      uint64                             uint8               uint8                               float64                                         uint8                            int16                             uint8                             uint8                           int16                         uint8                            uint8                          uint64                                       uint8                                uint8                                int32            float64            float64         float64         uint32                  uint8         float32             float32            uint8  float32           float32           float32                                     uint8                                      uint8                                     uint8                                     uint8                                     uint8                                     uint8                                     uint8                                  uint8                                   uint8                                  uint8                                  uint8                                  uint8                                  uint8                                  uint8                          uint64                     float32                      float32                     float32                     float32                     float32                     float32                     float32                              float32                               float32                              float32                              float32                              float32                              float32                              float32                              float32                               float32                              float32                              float32                              float32                              float32                              float32                                    uint8                                     uint8                                    uint8                                    uint8                                    uint8                                    uint8                                    uint8                        float32                         float32                        float32                        float32                        float32                        float32                        float32                                 float32                                  float32                                 float32                                 float32                                 float32                                 float32                                 float32                                 float32                                  float32                                 float32                                 float32                                 float32                                 float32                                 float32                       float32                        float32                       float32                       float32                       float32                       float32                       float32                                float32                                 float32                                float32                                float32                                float32                                float32                                float32                                float32                                 float32                                float32                                float32                                float32                                float32                                float32                 uint8     float32              float32              float32    float32             float32             float32        string        string  datetime64[ns]  geometry  category[known]  category[known]

In [8]:
def calc(df):
    import h3pandas
    return df.h3.h3_to_parent(5).set_index('h3_05')

df = ddf.head()
meta = calc(df)
meta

,shot_number,lat_lowestmode_l2a,rh_000_l2a,rh_001_l2a,rh_002_l2a,rh_003_l2a,rh_004_l2a,rh_005_l2a,rh_006_l2a,rh_007_l2a,...,wsci_xy_pi_upper_l4c,wsci_z_l4c,wsci_z_pi_lower_l4c,wsci_z_pi_upper_l4c,root_beam_l4c,root_file_l4c,datetime,geometry,h3_03,year
h3_05,,,,,,,,,,,,,,,,,,,,,
85804cd3fffffff,25760100200097278,0.346218,-5.84,-5.65,-5.46,-5.28,-5.05,-4.86,-4.64,-4.41,...,6.282208,5.329969,4.264297,6.395641,BEAM0001,GEDI04_C_2019147173201_O02576_02_T03624_02_001...,2019-05-27 22:54:58.480494738,POINT (-50.77809 0.34622),83804cfffffffff,2019
85804cd3fffffff,25760100200097279,0.346642,-1.72,-1.46,-1.23,-1.01,-0.82,-0.67,-0.52,-0.37,...,6.273551,5.628924,5.072198,6.185649,BEAM0001,GEDI04_C_2019147173201_O02576_02_T03624_02_001...,2019-05-27 22:54:58.488758802,POINT (-50.77779 0.34664),83804cfffffffff,2019
85804cd3fffffff,25760100200097280,0.347063,-3.74,-3.55,-3.33,-3.14,-2.95,-2.73,-2.54,-2.35,...,6.337328,5.270486,4.204814,6.336158,BEAM0001,GEDI04_C_2019147173201_O02576_02_T03624_02_001...,2019-05-27 22:54:58.497022629,POINT (-50.7775 0.34706),83804cfffffffff,2019
85804cd3fffffff,25760100200097281,0.347483,-1.34,-1.16,-1.01,-0.82,-0.67,-0.52,-0.41,-0.26,...,-9999.000000,-9999.000000,-9999.000000,-9999.000000,BEAM0001,GEDI04_C_2019147173201_O02576_02_T03624_02_001...,2019-05-27 22:54:58.505286694,POINT (-50.7772 0.34748),83804cfffffffff,2019
85804cd3fffffff,25760100200097282,0.347907,-2.69,-2.54,-2.39,-2.24,-2.09,-1.94,-1.79,-1.68,...,6.611540,4.933245,3.867573,5.998917,BEAM0001,GEDI04_C_2019147173201_O02576_02_T03624_02_001...,2019-05-27 22:54:58.513550758,POINT (-50.7769 0.34791),83804cfffffffff,2019

In [31]:
a = ddf.query("wsci_l4c > 0").map_partitions(calc, meta=meta).groupby('h3_03', observed=True)[['wsci_l4c','agbd_l4a']].apply(lambda x: x.groupby(level=0).agg('mean'))
a = a.map_partitions(lambda x: x.droplevel(0))

/tmp/ipykernel_2535577/1337503224.py:1: UserWarning: `meta` is not specified, inferred from partial data.
Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result

  a = ddf.query("wsci_l4c > 0").map_partitions(calc, meta=meta).groupby('h3_03', observed=True)[['wsci_l4c','agbd_l4a']].apply(lambda x: x.groupby(level=0).agg('mean'))

In [1]:
from cmr import GranuleQuery

api = GranuleQuery()
granules = api.short_name("AST_L1T").point(-112.73, 42.5).get(3)

print("Granule Titles:")
for granule in granules:
  print(granule["title"])

Granule Titles:
AST_L1T_00407152000184011_20250126003739
AST_L1T_00407152000184020_20250126003801
AST_L1T_00407222000184605_20250126070347

In [26]:
api.bounding_box(-112.70, 42.5, -110, 44.5)

polygons = []
api.polygon([(-100, 40), (-110, 40), (-105, 38), (-100, 40)])
polygons.append(api.params.pop('polygon'))
api.polygon([(-100, 41), (-110, 40), (-105, 38), (-100, 41)])
polygons.append(api.params.pop('polygon'))

api.params['polygon'] = polygons

In [38]:
api.params

{'short_name': 'AST_L1T',
 'point': ['-112.73,42.5'],
 'bounding_box': '-112.7,42.5,-110.0,44.5',
 'polygon': ['-100.0,40.0,-110.0,40.0,-105.0,38.0,-100.0,40.0',
  '-100.0,41.0,-110.0,40.0,-105.0,38.0,-100.0,41.0']}

In [32]:
api.options['polygon'] = {'or': True}

In [33]:
api._build_url()

'https://cmr.earthdata.nasa.gov/search/granules.json?short_name=AST_L1T&point[]=-112.73,42.5&bounding_box=-112.7,42.5,-110.0,44.5&polygon[]=-100.0,40.0,-110.0,40.0,-105.0,38.0,-100.0,40.0&polygon[]=-100.0,41.0,-110.0,40.0,-105.0,38.0,-100.0,41.0&options[polygon][or]=true'

In [35]:
import earthaccess
auth = earthaccess.login()

In [42]:
api.params['polygon']

['-100.0,40.0,-110.0,40.0,-105.0,38.0,-100.0,40.0',
 '-100.0,41.0,-110.0,40.0,-105.0,38.0,-100.0,41.0']

In [47]:
auth.__dict__

{'authenticated': True,
 'token': {'access_token': 'eyJ0eXAiOiJKV1QiLCJvcmlnaW4iOiJFYXJ0aGRhdGEgTG9naW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ.eyJ0eXBlIjoiVXNlciIsInVpZCI6InRpYWdvZGMiLCJleHAiOjE3NjI1NTk5OTksImlhdCI6MTc1NzM2MjM0NCwiaXNzIjoiaHR0cHM6Ly91cnMuZWFydGhkYXRhLm5hc2EuZ292IiwiaWRlbnRpdHlfcHJvdmlkZXIiOiJlZGxfb3BzIiwiYWNyIjoiZWRsIiwiYXNzdXJhbmNlX2xldmVsIjozfQ.PnOM_OmdlsjsDoMyCW6EV5uL8D9hQO7mPg1w5vlOFxc1uTljgKDYdL7u0vBoUO0HbmGxZKCDnS8HaKByoK-CMdWaCcey3MGshg2T6BtDVA6sxi4f1hq4ZgOouSlt9qZVLBUCN0sNvP7CCm9VAiUN0EDvrBrtoCt2QhdJ1bmgvDtgU3WOmwAKQ4aPhZInehFmsTWTk_lWYSR4EdgXXAZNbUhSXOLMRBHQsd1HYF5FqZAyQ6-vwLYzZ5yp7b9Dk0QyuAFVLTx_BJi50hvIqilWJsIZ0hao55X4DejKc7sSwxmR2lcTPKIn_a8GO7U0VGyic5BapOGWTRPUoF4fxzczVw',
  'token_type': 'Bearer',
  'expiration_date': '11/07/2025'},
 'system': System(cmr_base_url='https://cmr.earthdata.nasa.gov/search/', edl_hostname='urs.earthdata.nasa.gov'),
 'EDL_FIND_OR_CREATE_TOKEN_URL': 'https://urs.earthdata.nasa.gov/api/users/find_or_create_token',
 '_eula_url': 'https://urs.earthdata.nasa.gov/users/earthaccess/unaccepted_eulas',
 '_apps_url': 'https://urs.earthdata.nasa.gov/application_search',
 'username': 'tiagodc',
 'password': 'vjN2Z7YkMspVi6S@'}

In [41]:
search_params = {'polygon':api.params['polygon']}
granules = earthaccess.search_data(**search_params)

ValueError: A polygon requires at least 4 pairs of coordinates; got 2.