In [1]:
import sys, os
path = os.path.abspath('../src')
sys.path.insert(0, path)

In [2]:
from gedih3.config import GH3_DEFAULT_DOWNLOAD_DIR, GH3_DEFAULT_SOC_DIR, GEDI_START_DATE
from gedih3.gedidriver import soc_file_tree, dask_h5_merged
from gedih3.gh3builder import h3_index_df, build_h3db_from_soc

/home/tiago/miniconda3/envs/gedih3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from dask.distributed import Client
import dask.dataframe
import dask_geopandas
client = Client(processes=True, threads_per_worker=1, n_workers=2)
client

2025-10-04 23:30:28,801 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle bf198abf548d85d5ab2db5e34766bf0f initialized by task ('shuffle-transfer-bf198abf548d85d5ab2db5e34766bf0f', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:30:31,689 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle bf198abf548d85d5ab2db5e34766bf0f deactivated due to stimulus 'task-finished-1759635031.6808445'
2025-10-04 23:31:32,361 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 8cd9aa7bc5d0e88f4dc504923edf50e0 initialized by task ('shuffle-transfer-8cd9aa7bc5d0e88f4dc504923edf50e0', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:31:36,966 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 8cd9aa7bc5d0e88f4dc504923edf50e0 deactivated due to stimulus 'task-finished-1759635096.955136'
2025-10-04 23:32:15,471 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 80950a65989b3d8816ed69070a8b7ca1 initialized by task ('shuffle-transfer-80950a65989b3d8816ed69070a8b7ca1', 0) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:32:23,394 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 80950a65989b3d8816ed69070a8b7ca1 deactivated due to stimulus 'task-finished-1759635143.3922594'
2025-10-04 23:32:39,567 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3dc06952aecbf338fe5d447065d7fb2d initialized by task ('shuffle-transfer-3dc06952aecbf338fe5d447065d7fb2d', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:32:44,169 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3dc06952aecbf338fe5d447065d7fb2d deactivated due to stimulus 'task-finished-1759635164.1602283'
2025-10-04 23:33:08,697 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c502d9ed647d4c4ca628df30d8183dbb initialized by task ('shuffle-transfer-c502d9ed647d4c4ca628df30d8183dbb', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:33:13,902 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle c502d9ed647d4c4ca628df30d8183dbb deactivated due to stimulus 'task-finished-1759635193.8909085'
2025-10-04 23:38:49,346 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 6eccf769f67309a83bcedd0b4bc2d9b9 initialized by task ('shuffle-transfer-6eccf769f67309a83bcedd0b4bc2d9b9', 0) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:38:57,397 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 6eccf769f67309a83bcedd0b4bc2d9b9 deactivated due to stimulus 'task-finished-1759635537.3772724'
2025-10-04 23:40:00,400 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 39430356d37cb12bf53da392989f9100 initialized by task ('shuffle-transfer-39430356d37cb12bf53da392989f9100', 0) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:40:07,515 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 39430356d37cb12bf53da392989f9100 deactivated due to stimulus 'task-finished-1759635607.5092506'
2025-10-04 23:40:38,158 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 1ee5711beb5008e26e6eb354719ca7f0 initialized by task ('shuffle-transfer-1ee5711beb5008e26e6eb354719ca7f0', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:40:40,785 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 1ee5711beb5008e26e6eb354719ca7f0 deactivated due to stimulus 'task-finished-1759635640.7774456'
2025-10-04 23:40:57,694 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 53932abe3c4d48b18e3ac276b456cca9 initialized by task ('shuffle-transfer-53932abe3c4d48b18e3ac276b456cca9', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:41:00,101 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 53932abe3c4d48b18e3ac276b456cca9 deactivated due to stimulus 'task-finished-1759635660.0881438'
2025-10-04 23:42:50,616 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7a3180180af2b921db55735b79aca081 initialized by task ('shuffle-transfer-7a3180180af2b921db55735b79aca081', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:42:53,744 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 7a3180180af2b921db55735b79aca081 deactivated due to stimulus 'task-finished-1759635773.7398632'
2025-10-04 23:44:04,246 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 11dd7c42d9b1f7d0c7c3deaf5266753c initialized by task ('shuffle-transfer-11dd7c42d9b1f7d0c7c3deaf5266753c', 1) executed on worker tcp://127.0.0.1:45789
2025-10-04 23:44:06,664 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 11dd7c42d9b1f7d0c7c3deaf5266753c deactivated due to stimulus 'task-finished-1759635846.6587057'

In [9]:
ddf = dask_geopandas.read_parquet('../tmp', gather_spatial_partitions=False)

In [34]:
def calc(df):
    import h3pandas
    return df.h3.h3_to_parent(5).set_index('h3_05')

meta = calc(df)
meta

,shot_number,elev_lowestmode_l2a,lon_lowestmode_l2a,delta_time_l2a,rh_000_l2a,rh_001_l2a,rh_002_l2a,rh_003_l2a,rh_004_l2a,rh_005_l2a,...,wsci_xy_pi_upper_l4c,wsci_z_l4c,wsci_z_pi_lower_l4c,wsci_z_pi_upper_l4c,root_beam_l4c,root_file_l4c,datetime,geometry,h3_03,year
h3_05,,,,,,,,,,,,,,,,,,,,,
85804c6ffffffff,87320100300498317,57.338013,-50.832984,7.851114e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,-9999.0,-9999.0,-9999.0,-9999.0,BEAM0001,GEDI04_C_2020179153021_O08732_03_T03677_02_001_01_V002.h5,2020-06-27 21:39:04.218766451,POINT (-50.83298 1.6027),83804cfffffffff,2020
85804c6ffffffff,87320100300498318,56.974083,-50.832686,7.851114e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,-9999.0,-9999.0,-9999.0,-9999.0,BEAM0001,GEDI04_C_2020179153021_O08732_03_T03677_02_001_01_V002.h5,2020-06-27 21:39:04.227030993,POINT (-50.83269 1.60228),83804cfffffffff,2020
85804c6ffffffff,87320100300498319,57.206856,-50.832388,7.851114e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,-9999.0,-9999.0,-9999.0,-9999.0,BEAM0001,GEDI04_C_2020179153021_O08732_03_T03677_02_001_01_V002.h5,2020-06-27 21:39:04.235295057,POINT (-50.83239 1.60186),83804cfffffffff,2020
85804c6ffffffff,87320100300498320,57.221401,-50.832089,7.851114e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,-9999.0,-9999.0,-9999.0,-9999.0,BEAM0001,GEDI04_C_2020179153021_O08732_03_T03677_02_001_01_V002.h5,2020-06-27 21:39:04.243558884,POINT (-50.83209 1.60145),83804cfffffffff,2020
85804c6ffffffff,87320100300498321,57.393181,-50.831791,7.851114e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,-9999.0,-9999.0,-9999.0,-9999.0,BEAM0001,GEDI04_C_2020179153021_O08732_03_T03677_02_001_01_V002.h5,2020-06-27 21:39:04.251822948,POINT (-50.83179 1.60103),83804cfffffffff,2020

In [ ]:
a = ddf.query("wsci_l4c > 0").map_partitions(calc, meta=meta).groupby('h3_03', observed=True)[['wsci_l4c','agbd_l4a']].apply(lambda x: x.groupby(level=0).agg('mean'))
a = a.map_partitions(lambda x: x.droplevel(0))

/tmp/ipykernel_835595/1933781529.py:1: UserWarning: `meta` is not specified, inferred from partial data.
Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result

  a = ddf.query("wsci_l4c > 0").map_partitions(calc, meta=meta).groupby('h3_03', observed=True)[['wsci_l4c','agbd_l4a']].apply(lambda x: x.groupby(level=0).agg('mean'))

In [69]:
a.compute()

                  wsci_l4c     agbd_l4a
h3_05
85804103fffffff   7.801361 -4579.232422
85804107fffffff   8.467340  -328.460724
8580410bfffffff   7.000627     1.314341
8580410ffffffff   7.969027 -5810.027832
85804113fffffff  10.157640    55.032093
...                    ...          ...
85804ec7fffffff   8.622376  -848.565979
85804ecbfffffff   8.066348 -9999.000000
85804ecffffffff   8.746167 -9999.000000
85804ed3fffffff   7.671892 -9999.000000
85804ed7fffffff   8.450148 -3802.347900

[72 rows x 2 columns]