In [1]:
import sys, os
path = os.path.abspath('../src')
sys.path.insert(0, path)

In [2]:
import dask_geopandas

In [9]:
hexes = ['83804cfffffffff', '83804efffffffff']
d = "/gpfs/data1/vclgp/decontot/repos/gedih3/tmp/h3"
ddf = dask_geopandas.read_parquet(d, gather_spatial_partitions=False, filters=[('h3_03', 'in', hexes)])
ddf

Dask GeoDataFrame Structure:
               shot_number elev_lowestmode_l2a lat_lowestmode_l2a quality_flag_l2a lon_lowestmode_l2a delta_time_l2a rh_000_l2a rh_001_l2a rh_002_l2a rh_003_l2a rh_004_l2a rh_005_l2a rh_006_l2a rh_007_l2a rh_008_l2a rh_009_l2a rh_010_l2a rh_011_l2a rh_012_l2a rh_013_l2a rh_014_l2a rh_015_l2a rh_016_l2a rh_017_l2a rh_018_l2a rh_019_l2a rh_020_l2a rh_021_l2a rh_022_l2a rh_023_l2a rh_024_l2a rh_025_l2a rh_026_l2a rh_027_l2a rh_028_l2a rh_029_l2a rh_030_l2a rh_031_l2a rh_032_l2a rh_033_l2a rh_034_l2a rh_035_l2a rh_036_l2a rh_037_l2a rh_038_l2a rh_039_l2a rh_040_l2a rh_041_l2a rh_042_l2a rh_043_l2a rh_044_l2a rh_045_l2a rh_046_l2a rh_047_l2a rh_048_l2a rh_049_l2a rh_050_l2a rh_051_l2a rh_052_l2a rh_053_l2a rh_054_l2a rh_055_l2a rh_056_l2a rh_057_l2a rh_058_l2a rh_059_l2a rh_060_l2a rh_061_l2a rh_062_l2a rh_063_l2a rh_064_l2a rh_065_l2a rh_066_l2a rh_067_l2a rh_068_l2a rh_069_l2a rh_070_l2a rh_071_l2a rh_072_l2a rh_073_l2a rh_074_l2a rh_075_l2a rh_076_l2a rh_077_l2a rh_078_l2a rh_079_l2a rh_080_l2a rh_081_l2a rh_082_l2a rh_083_l2a rh_084_l2a rh_085_l2a rh_086_l2a rh_087_l2a rh_088_l2a rh_089_l2a rh_090_l2a rh_091_l2a rh_092_l2a rh_093_l2a rh_094_l2a rh_095_l2a rh_096_l2a rh_097_l2a rh_098_l2a rh_099_l2a rh_100_l2a root_beam_l2a root_file_l2a agbd_l4a root_beam_l4a root_file_l4a wsci_l4c root_beam_l4c root_file_l4c        datetime  geometry            h3_03             year
npartitions=14
                    uint64             float32            float64            uint8            float64        float64    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32    float32        string        string  float32        string        string  float32        string        string  datetime64[ns]  geometry  category[known]  category[known]
                       ...                 ...                ...              ...                ...            ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...           ...           ...      ...           ...           ...      ...           ...           ...             ...       ...              ...              ...
...                    ...                 ...                ...              ...                ...            ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...           ...           ...      ...           ...           ...      ...           ...           ...             ...       ...              ...              ...
                       ...                 ...                ...              ...                ...            ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...           ...           ...      ...           ...           ...      ...           ...           ...             ...       ...              ...              ...
                       ...                 ...                ...              ...                ...            ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...           ...           ...      ...           ...           ...      ...           ...           ...             ...       ...              ...              ...
Dask Name: read_parquet, 1 expression
Expr=FromGraph(c87a140)

In [7]:
ddf.head()

,shot_number,elev_lowestmode_l2a,lat_lowestmode_l2a,quality_flag_l2a,lon_lowestmode_l2a,delta_time_l2a,rh_000_l2a,rh_001_l2a,rh_002_l2a,rh_003_l2a,...,agbd_l4a,root_beam_l4a,root_file_l4a,wsci_l4c,root_beam_l4c,root_file_l4c,datetime,geometry,h3_03,year
h3_12,,,,,,,,,,,,,,,,,,,,,
8c804ca4ba4b1ff,54070300300499774,75.797081,1.017681,1,-51.631072,5.998169e+07,-1.34,-0.74,-0.26,0.14,...,169.466583,BEAM0011,GEDI04_A_2019330042559_O05407_03_T01642_02_002...,10.754507,BEAM0011,GEDI04_C_2019330042559_O05407_03_T01642_02_001...,2019-11-26 10:34:52.788519621,POINT (-51.63107 1.01768),83804cfffffffff,2019
8c804ca4ba4a9ff,54070300300499775,74.296371,1.017259,1,-51.630775,5.998169e+07,-1.75,-1.27,-0.78,-0.26,...,160.877319,BEAM0011,GEDI04_A_2019330042559_O05407_03_T01642_02_002...,10.455272,BEAM0011,GEDI04_C_2019330042559_O05407_03_T01642_02_001...,2019-11-26 10:34:52.796783686,POINT (-51.63077 1.01726),83804cfffffffff,2019
8c804ca4ba433ff,54070300300499776,63.679214,1.016832,1,-51.630478,5.998169e+07,-2.95,-2.39,-1.90,-1.49,...,292.847168,BEAM0011,GEDI04_A_2019330042559_O05407_03_T01642_02_002...,10.811131,BEAM0011,GEDI04_C_2019330042559_O05407_03_T01642_02_001...,2019-11-26 10:34:52.805047750,POINT (-51.63048 1.01683),83804cfffffffff,2019
8c804ca4ba407ff,54070300300499777,71.556938,1.016415,1,-51.630182,5.998169e+07,-7.25,-6.81,-6.43,-6.09,...,166.550369,BEAM0011,GEDI04_A_2019330042559_O05407_03_T01642_02_002...,10.424293,BEAM0011,GEDI04_C_2019330042559_O05407_03_T01642_02_001...,2019-11-26 10:34:52.813311815,POINT (-51.63018 1.01641),83804cfffffffff,2019
8c804ca4ba461ff,54070300300499778,59.743317,1.015988,1,-51.629885,5.998169e+07,-1.75,-1.12,-0.48,0.18,...,351.558319,BEAM0011,GEDI04_A_2019330042559_O05407_03_T01642_02_002...,10.830250,BEAM0011,GEDI04_C_2019330042559_O05407_03_T01642_02_001...,2019-11-26 10:34:52.821575642,POINT (-51.62988 1.01599),83804cfffffffff,2019